Add TableTranslator , ScriptTranslator in Component
hchunhui/librime-lua pull request #287
Opened 2023-10-26 00:52 UTC by shewer

提供 設定開關   enable_....    ,   user_dict update   同 memory  callback  
table_translator  
script_translator

2023-12-15 02:32 UTC, mokapsing commented
希望早点合入

2024-01-20 02:40 UTC, hchunhui requested changes
这几个地方还需要再完善一下

2024-01-20 02:40 UTC, hchunhui commented on src/lib/luatype_boost_optional.h
这里好像还是以前的代码

2024-01-20 02:40 UTC, hchunhui commented on src/table_translator.cc
> +  memorize_callback_ = lua_->getglobal("___");
这里的 "___" 看起来不太对

2024-02-02 04:21 UTC, mokapsing commented
> 这几个地方还需要再完善一下

再看下呢，非常需要这个功能

2024-02-02 12:04 UTC, merged